// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config';
import dotenv from 'dotenv';
import path from 'node:path';

const envFile = process.env.NODE_ENV === 'production' ? '.env.prod' : '.env.dev';
dotenv.config({
   path: path.resolve(process.cwd(), envFile),
});

export default defineConfig({
   schema: 'prisma/schema.prisma',
   migrations: {
      path: 'prisma/migrations',
      seed: 'tsx prisma/seed.ts',
   },
   datasource: {
      url: process.env.DATABASE_URL as string,
   },
});
